---
title: "R Notebook"
output:
  pdf_document: default
  html_document:
    df_print: paged
params:
  new_title: My Title
code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r Load In Packages and Data}
require(parallel)
require(tidyverse)
require(sf)
require(tmap)
require(tmaptools)
require(xts)

ONSAllHouseData<-read.csv("NewAllHousePriceONS.csv",header = T)
DetachedHousePrices<-read.csv("DetachedHousePrices.csv", header = T)
SemiDetachedHousePrices<-read.csv("SemiDetachedPrices.csv", header = T)
TerracedHousePrices<-read.csv("TerracedHousePrices.csv", header = T)
FlatPrices<-read.csv("FlatPrices.csv", header = T)

MSOA<-st_read("/Users/Nasir/Downloads/infuse_msoa_lyr_2011_clipped",stringsAsFactors=F)



```

```{r Merging all property types}

DetachedHousePrices$ProxyIndicator<-1
SemiDetachedHousePrices$ProxyIndicator<-2
TerracedHousePrices$ProxyIndicator<-3
FlatPrices$ProxyIndicator<-4

AllPropertyTypes<-rbind(DetachedHousePrices,SemiDetachedHousePrices,TerracedHousePrices,FlatPrices)

# Remove NAs and Commas 
AllPropertyTypes<-AllPropertyTypes %>% 
  mutate(across(.cols = contains("Year.ending"), ~replace(., .<0,NA))) %>%
  mutate(across(.cols = contains("Year.ending"),~str_replace_all(.,",","")))


# Inflation adjustment

AllPropertyTypes<-AllPropertyTypes %>% mutate(across(.cols = contains("Year.ending"), ~as.numeric(.)))

AllPropertyTypes<-AllPropertyTypes %>%
  mutate(across(.cols = contains("1996"), ~.*1.345)) %>%
  mutate(across(.cols = contains("1997"), ~as.numeric(.)*1.345)) %>%
  mutate(across(.cols = contains("1998"), ~as.numeric(.)*1.338)) %>%
  mutate(across(.cols = contains("1999"), ~as.numeric(.)*1.332)) %>%
  mutate(across(.cols = contains("2000"), ~as.numeric(.)*1.320)) %>%
  mutate(across(.cols = contains("2001"), ~as.numeric(.)*1.312)) %>%
  mutate(across(.cols = contains("2002"), ~as.numeric(.)*1.298)) %>%
  mutate(across(.cols = contains("2003"), ~as.numeric(.)*1.281)) %>%
  mutate(across(.cols = contains("2004"), ~as.numeric(.)*1.263)) %>%
  mutate(across(.cols = contains("2005"), ~as.numeric(.)*1.243)) %>%
  mutate(across(.cols = contains("2006"), ~as.numeric(.)*1.222)) %>%
  mutate(across(.cols = contains("2007"), ~as.numeric(.)*1.201)) %>%
  mutate(across(.cols = contains("2008"), ~as.numeric(.)*1.176)) %>%
  mutate(across(.cols = contains("2009"), ~as.numeric(.)*1.163)) %>%
  mutate(across(.cols = contains("2010"), ~as.numeric(.)*1.149)) %>%
  mutate(across(.cols = contains("2011"), ~as.numeric(.)*1.132)) %>%
  mutate(across(.cols = contains("2012"), ~as.numeric(.)*1.117)) %>%
  mutate(across(.cols = contains("2013"), ~as.numeric(.)*1.102)) %>%
  mutate(across(.cols = contains("2014"), ~as.numeric(.)*1.086)) %>%
  mutate(across(.cols = contains("2015"), ~as.numeric(.)*1.080)) %>%
  mutate(across(.cols = contains("2016"), ~as.numeric(.)*1.060)) %>%
  mutate(across(.cols = contains("2017"), ~as.numeric(.)*1.042)) %>%
  mutate(across(.cols = contains("2018"), ~as.numeric(.)*1.021)) %>%
  mutate(across(.cols = contains("2019"), ~as.numeric(.)*1))



# Pivot longer and make: Avg Year Price, Avg Year SD

AllPropertyTypesLong<-AllPropertyTypes %>%
  pivot_longer(cols = contains("Year"), names_to = "Year", values_to = "Price") %>%
  mutate(Year=str_replace_all(AllPropertyTypesLong$Year,"\\.","")) %>%
  mutate(QuarterAndYear = as.character(str_sub(Year, start = -7))) %>%
  mutate(Year = as.character(str_sub(Year, start = -4))) %>%
  mutate(Price = as.numeric(Price)) %>%
  group_by(MSOA.name, Year,ProxyIndicator) %>%
  mutate(AvgYearPrice = median(Price,na.rm = T)) %>%
  ungroup() %>%
  group_by(MSOA.name,Year,ProxyIndicator) %>%
  mutate(AvgYearSD = sd(as.numeric(Price,na.rm = T))) %>%
  ungroup() 

# Dataset by avg year

AllPropertyTypesLong_2019_2020 <- AllPropertyTypesLong %>%
  group_by(MSOA.name, ProxyIndicator) %>%
  filter(Year %in% c(2019,2020), !duplicated(Year)) %>%
  mutate(TwentyNineteen_TwentyTwenty = AvgYearPrice - lag(AvgYearPrice)) %>% 
  mutate(PercTwentyNineteen_TwentyTwenty = (TwentyNineteen_TwentyTwenty / first(AvgYearPrice)) *100) %>%
  ungroup()


```

```{r Clean Data at All property types - not combined}

# Remove NAs and Commas 
ONSAllHouseData<-ONSAllHouseData %>% 
  mutate(across(.cols = contains("Year.ending"), ~replace(., .<0,NA))) %>%
  mutate(across(.cols = contains("Year.ending"),~str_replace_all(.,",","")))

# InflationAdjustment
Inflation<-read.csv("GDP Deflator 2019.csv")

ONSAllHouseData<-ONSAllHouseData %>% mutate(across(.cols = contains("Year.ending"), ~as.numeric(.)))

ONSAllHouseData<-ONSAllHouseData %>%
  mutate(across(.cols = contains("1996"), ~.*1.345)) %>%
  mutate(across(.cols = contains("1997"), ~as.numeric(.)*1.345)) %>%
  mutate(across(.cols = contains("1998"), ~as.numeric(.)*1.338)) %>%
  mutate(across(.cols = contains("1999"), ~as.numeric(.)*1.332)) %>%
  mutate(across(.cols = contains("2000"), ~as.numeric(.)*1.320)) %>%
  mutate(across(.cols = contains("2001"), ~as.numeric(.)*1.312)) %>%
  mutate(across(.cols = contains("2002"), ~as.numeric(.)*1.298)) %>%
  mutate(across(.cols = contains("2003"), ~as.numeric(.)*1.281)) %>%
  mutate(across(.cols = contains("2004"), ~as.numeric(.)*1.263)) %>%
  mutate(across(.cols = contains("2005"), ~as.numeric(.)*1.243)) %>%
  mutate(across(.cols = contains("2006"), ~as.numeric(.)*1.222)) %>%
  mutate(across(.cols = contains("2007"), ~as.numeric(.)*1.201)) %>%
  mutate(across(.cols = contains("2008"), ~as.numeric(.)*1.176)) %>%
  mutate(across(.cols = contains("2009"), ~as.numeric(.)*1.163)) %>%
  mutate(across(.cols = contains("2010"), ~as.numeric(.)*1.149)) %>%
  mutate(across(.cols = contains("2011"), ~as.numeric(.)*1.132)) %>%
  mutate(across(.cols = contains("2012"), ~as.numeric(.)*1.117)) %>%
  mutate(across(.cols = contains("2013"), ~as.numeric(.)*1.102)) %>%
  mutate(across(.cols = contains("2014"), ~as.numeric(.)*1.086)) %>%
  mutate(across(.cols = contains("2015"), ~as.numeric(.)*1.080)) %>%
  mutate(across(.cols = contains("2016"), ~as.numeric(.)*1.060)) %>%
  mutate(across(.cols = contains("2017"), ~as.numeric(.)*1.042)) %>%
  mutate(across(.cols = contains("2018"), ~as.numeric(.)*1.021)) %>%
  mutate(across(.cols = contains("2019"), ~as.numeric(.)*1))

# Pivot longer and make: Avg Year Price, Avg Year SD

ONSLong<-ONSAllHouseData %>%
  pivot_longer(cols = contains("Year"), names_to = "Year", values_to = "Price") %>%
  mutate(Year=str_replace_all(ONSLong$Year,"\\.","")) %>%
  mutate(QuarterAndYear = as.character(str_sub(Year, start = -7))) %>%
  mutate(Year = as.character(str_sub(Year, start = -4))) %>%
  mutate(Price = as.numeric(Price)) %>%
  group_by(MSOA.name, Year) %>%
  mutate(AvgYearPrice = median(Price,na.rm = T)) %>%
  ungroup() %>%
  group_by(MSOA.name,Year) %>%
  mutate(AvgYearSD = sd(as.numeric(Price,na.rm = T))) %>%
  ungroup() 
  

# A dataset of only 2019-2020 by quarter

ONSLongFor2019_To_2020_Quarterly <- ONSLong %>%
  group_by(MSOA.name) %>%
  filter(Year %in% c(2019,2020)) %>%
  mutate(PriceGrowth = Price - lag(Price)) %>%
  mutate(TwentyNineteen_TwentyTwenty = AvgYearPrice - lag(AvgYearPrice)) %>% 
  mutate(PercTwentyNineteen_TwentyTwenty = (TwentyNineteen_TwentyTwenty / first(AvgYearPrice)) *100) %>%
  ungroup()

# Dataset by avg year

ONSLongFor2019_To_2020 <- ONSLong %>%
  group_by(MSOA.name) %>%
  filter(Year %in% c(2019,2020), !duplicated(Year)) %>%
  mutate(TwentyNineteen_TwentyTwenty = AvgYearPrice - lag(AvgYearPrice)) %>% 
  mutate(PercTwentyNineteen_TwentyTwenty = (TwentyNineteen_TwentyTwenty / first(AvgYearPrice)) *100) %>%
  ungroup()

```

```{r Troubleshooting}
Test<-as.data.frame(setdiff(ONSLong$MSOA.name,ONSLong2$MSOA.name))
Test<- Test %>% rename(MSOA.name = `setdiff(ONSLong$MSOA.name, ONSLong2$MSOA.name)`)
  
Match1<-merge(ONSLong,Test, by = "MSOA.name", all.y = T)

Match1<-Match1 %>% 
  drop_na(Region)

length(unique(ONSLong$MSOA.name[(ONSLong$Region=="London")]))

LondonBoroughs<-ONSLong2 %>% 
  filter(Region == "London" & Year %in% c(1996,2020)) %>%
  distinct(Local.authority.name, .keep_all = T)

  gg_miss_fct(x = DetachedHousePrices, fct = Region)

```

```{r Descriptive Mapping}
# Map MSOA to local regions
MSOARegions<-read.csv("RegionsMSOA.csv",header = T)

ONSLong$Region=MSOARegions$RGN11NM[match(ONSLong$MSOA.name,MSOARegions$MSOA11NM)]
ONSLong$geo_label<-ONSLong$MSOA.name

JoinesONSHouseData<-inner_join(MSOA,ONSLong)

tmap_mode("plot")
tmap_last()
```

```{r All UK Map}

# Output the image
tiff("AllUKMap.jpeg", units="in", width=10, height=6, res=100)

# Map it - takes a while - tm_polygons is the variable you want to map and id is your geographical information
tm_shape(JoinesONSHouseData) + tm_polygons("PercNinetySixToTwentyTwenty", id = "geo_label", border.alpha = 0.2,title = "Price Growth 1996 to 2020", style = "quantile",legend.hist = T,palette = get_brewer_pal(palette = "RdYlBu", n= 6, plot = T))+ tm_layout(panel.label.size = 0.8, panel.label.fontface = "bold",title.fontface = "bold", legend.outside = T, bg.color = "transparent")

# Have to turn off where the image will sink  
dev.off()

```

```{r London mapping}

# Output the image
tiff("AllLondon.jpeg", units="in", width=10, height=6, res=1000)

# Map it - takes a while - tm_polygons is the variable you want to map and id is your geographical information
tm_shape(filter(JoinesONSHouseData, Region == "London")) + tm_polygons("PercNinetySixToTwentyTwenty", id = "geo_label", border.alpha = 0.2,title = "Price Growth 1996 to 2020 as a % - Inflation Adjusted", breaks = c(155,200,300,400,550,700,850,1000,1750),legend.hist = T,palette = get_brewer_pal(palette = "RdYlBu", n= 6, plot = T))+ tm_layout(main.title ="Most Areas in London Have Seen Substantial Price Growth",main.title.position = "center",panel.label.size = 0.8, panel.label.fontface = "bold",title.fontface = "bold", legend.outside = T, bg.color = "transparent") +tm_text("MSOA.name",size = 0.1)

# Have to turn off where the image will sink  
dev.off()



# Output the image
tiff("LondonFacet.jpeg", units="in", width=10, height=6, res=1000)

# Map it - takes a while - tm_polygons is the variable you want to map and id is your geographical information
tm_shape(filter(JoinesONSHouseData, Region == "London")) + tm_polygons("PercNinetySixToTwentyTwenty", id = "geo_label", border.alpha = 0.2,title = "Price Growth 1996 to 2020 as a % - Inflation Adjusted", breaks = c(155,200,300,400,550,700,850,1000,1750),legend.hist = T,palette = get_brewer_pal(palette = "RdYlBu", n= 6, plot = T))+ tm_layout(main.title ="Most Areas in London Have Seen Substantial Price Growth - Now Split By Borough",main.title.position = "center",panel.label.size = 0.8, panel.label.fontface = "bold",title.fontface = "bold", legend.outside = T, bg.color = "transparent") +tm_facets(by = "Local.authority.name") +tm_text("MSOA.name",size = 0.1) 

# Have to turn off where the image will sink  
dev.off()

```

```{r London 2019 to 2020 Mapping}
ONSLongFor2019_To_2020$Region=MSOARegions$RGN11NM[match(ONSLongFor2019_To_2020$MSOA.name,MSOARegions$MSOA11NM)]
ONSLongFor2019_To_2020$geo_label<-ONSLongFor2019_To_2020$MSOA.name

JoinedONS2019_2020<- inner_join(MSOA,ONSLongFor2019_To_2020) 

JoinedONS2019_2020 <- JoinedONS2019_2020 %>%  
    group_by(geo_label) %>%
    filter(!duplicated(PercTwentyNineteen_TwentyTwenty) & PercTwentyNineteen_TwentyTwenty !=0)

# Output the image
tiff("AllLondon_2019_2020.jpeg", units="in", width=10, height=6, res=500)

# Map it
tm_shape(filter(JoinedONS2019_2020, Region == "London")) + tm_polygons("PercTwentyNineteen_TwentyTwenty", id = "geo_label", border.alpha = 0.2,title = "Price Growth 2019 to 2020",breaks = c(-65,-50,-40,-20,-10,-5,0,5,10,15,30,45,100),legend.hist = T,palette = get_brewer_pal(palette = "RdYlBu", n= 6, plot = T), midpoint = NA)+ tm_layout(panel.label.size = 0.8, panel.label.fontface = "bold",title.fontface = "bold", legend.outside = T, bg.color = "transparent") +tm_text("MSOA.name",size = 0.1) 

# Have to turn off where the image will sink  
dev.off()

```

```{r London 2019 to 2020 with all property types}

AllPropertyTypesLong_2019_2020$Region=MSOARegions$RGN11NM[match(AllPropertyTypesLong_2019_2020$MSOA.name,MSOARegions$MSOA11NM)]
AllPropertyTypesLong_2019_2020$geo_label<-AllPropertyTypesLong_2019_2020$MSOA.name

AllPropertyTypesLong_2019_2020$ProxyIndicator<-factor(AllPropertyTypesLong_2019_2020$ProxyIndicator, levels = c(1,2,3,4), labels = c("Detached Houses", "Semi-Detached Houses", "Terraced Houses", "Flats & Maisonnetes"))


JoinedONS2019_2020_All_PropertyType<- inner_join(MSOA,AllPropertyTypesLong_2019_2020) 

# Output the image
tiff("AllLondon_2019_2020_All_Property.jpeg", units="in", width=10, height=6, res=1000)

# Map it
tm_shape(filter(JoinedONS2019_2020_All_PropertyType, Region == "London")) + tm_polygons("PercTwentyNineteen_TwentyTwenty", id = "geo_label", border.alpha = 0.2,title = "Price Growth Dec 2019 to Dec 2020",breaks = c(-80,-65,-50,-40,-20,-10,-5,0,5,10,15,30,45,60,90,120,150,175,200,225,250),legend.hist = T,palette = get_brewer_pal(palette = "RdYlBu", n= 6, plot = T), midpoint = NA)+tm_facets(by = "ProxyIndicator")+ tm_layout(panel.label.size = 0.8, panel.label.fontface = "bold",title.fontface = "bold", legend.outside = T, bg.color = "transparent") +tm_text("MSOA.name",size = 0.1) 

# Have to turn off where the image will sink  
dev.off()
```

```{r By London Borough}

### Wandsworth

# Output the image
tiff("Wandsworth.jpeg", units="in", width=10, height=6, res=500)

# Map it
tm_shape(filter(JoinedONS2019_2020_All_PropertyType, Local.authority.name == "Wandsworth")) + tm_polygons("PercTwentyNineteen_TwentyTwenty", id = "geo_label", border.alpha = 0.2,title = "Price Growth Dec 2019 to Dec 2020",breaks = c(-60,-50,-40,-20,-10,-5,0,5,10,15,30,45,50,55),legend.hist = T,palette = get_brewer_pal(palette = "RdYlBu", n= 6, plot = T), midpoint = NA)+tm_facets(by = "ProxyIndicator")+ tm_layout(panel.label.size = 0.8, panel.label.fontface = "bold",title.fontface = "bold", legend.outside = T, bg.color = "transparent") +tm_text("MSOA.name",size = 0.1) 

# Have to turn off where the image will sink  
dev.off()



### Kingston

# Output the image
tiff("Kingston.jpeg", units="in", width=10, height=6, res=500)

# Map it
tm_shape(filter(JoinedONS2019_2020_All_PropertyType, Local.authority.name == "Kingston upon Thames")) + tm_polygons("PercTwentyNineteen_TwentyTwenty", id = "geo_label", border.alpha = 0.2,title = "Price Growth Dec 2019 to Dec 2020",breaks = c(-21,-10,-3,-1,0,1,2,5,10,30,45,67),legend.hist = T,palette = get_brewer_pal(palette = "RdYlBu", n= 6, plot = T), midpoint = NA)+tm_facets(by = "ProxyIndicator")+ tm_layout(panel.label.size = 0.8, panel.label.fontface = "bold",title.fontface = "bold", legend.outside = T, bg.color = "transparent") +tm_text("MSOA.name",size = 0.1) 

# Have to turn off where the image will sink  
dev.off()

```


```{r Time Series Plotting}

TS_ONS_Flat_Data<-xts(JoinesONSHouseData,"Year")


```


```{r Descriptive plots}

```

```{r Predictions from Dec 2019 to Dec 2022}

# Do it for each property type

# Show effect of stamp duty

# Regression is probably time series?

# DiD?

```

```{r Mapping results}

```

